// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	auth "github.com/tinode/chat/server/auth"

	mock "github.com/stretchr/testify/mock"

	time "time"

	types "github.com/tinode/chat/server/store/types"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// AddRecord provides a mock function with given fields: rec, secret, remoteAddr
func (_m *AuthHandler) AddRecord(rec *auth.Rec, secret []byte, remoteAddr string) (*auth.Rec, error) {
	ret := _m.Called(rec, secret, remoteAddr)

	if len(ret) == 0 {
		panic("no return value specified for AddRecord")
	}

	var r0 *auth.Rec
	var r1 error
	if rf, ok := ret.Get(0).(func(*auth.Rec, []byte, string) (*auth.Rec, error)); ok {
		return rf(rec, secret, remoteAddr)
	}
	if rf, ok := ret.Get(0).(func(*auth.Rec, []byte, string) *auth.Rec); ok {
		r0 = rf(rec, secret, remoteAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Rec)
		}
	}

	if rf, ok := ret.Get(1).(func(*auth.Rec, []byte, string) error); ok {
		r1 = rf(rec, secret, remoteAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AsTag provides a mock function with given fields: token
func (_m *AuthHandler) AsTag(token string) string {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for AsTag")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Authenticate provides a mock function with given fields: secret, remoteAddr
func (_m *AuthHandler) Authenticate(secret []byte, remoteAddr string) (*auth.Rec, []byte, error) {
	ret := _m.Called(secret, remoteAddr)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *auth.Rec
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte, string) (*auth.Rec, []byte, error)); ok {
		return rf(secret, remoteAddr)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) *auth.Rec); ok {
		r0 = rf(secret, remoteAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Rec)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte, string) []byte); ok {
		r1 = rf(secret, remoteAddr)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte, string) error); ok {
		r2 = rf(secret, remoteAddr)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DelRecords provides a mock function with given fields: uid
func (_m *AuthHandler) DelRecords(uid types.Uid) error {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for DelRecords")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid) error); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenSecret provides a mock function with given fields: rec
func (_m *AuthHandler) GenSecret(rec *auth.Rec) ([]byte, time.Time, error) {
	ret := _m.Called(rec)

	if len(ret) == 0 {
		panic("no return value specified for GenSecret")
	}

	var r0 []byte
	var r1 time.Time
	var r2 error
	if rf, ok := ret.Get(0).(func(*auth.Rec) ([]byte, time.Time, error)); ok {
		return rf(rec)
	}
	if rf, ok := ret.Get(0).(func(*auth.Rec) []byte); ok {
		r0 = rf(rec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(*auth.Rec) time.Time); ok {
		r1 = rf(rec)
	} else {
		r1 = ret.Get(1).(time.Time)
	}

	if rf, ok := ret.Get(2).(func(*auth.Rec) error); ok {
		r2 = rf(rec)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetRealName provides a mock function with no fields
func (_m *AuthHandler) GetRealName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRealName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetResetParams provides a mock function with given fields: uid
func (_m *AuthHandler) GetResetParams(uid types.Uid) (map[string]interface{}, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetResetParams")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid) (map[string]interface{}, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(types.Uid) map[string]interface{}); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: jsonconf, name
func (_m *AuthHandler) Init(jsonconf json.RawMessage, name string) error {
	ret := _m.Called(jsonconf, name)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(json.RawMessage, string) error); ok {
		r0 = rf(jsonconf, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsInitialized provides a mock function with no fields
func (_m *AuthHandler) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsUnique provides a mock function with given fields: secret, remoteAddr
func (_m *AuthHandler) IsUnique(secret []byte, remoteAddr string) (bool, error) {
	ret := _m.Called(secret, remoteAddr)

	if len(ret) == 0 {
		panic("no return value specified for IsUnique")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, string) (bool, error)); ok {
		return rf(secret, remoteAddr)
	}
	if rf, ok := ret.Get(0).(func([]byte, string) bool); ok {
		r0 = rf(secret, remoteAddr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(secret, remoteAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestrictedTags provides a mock function with no fields
func (_m *AuthHandler) RestrictedTags() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RestrictedTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecord provides a mock function with given fields: rec, secret, remoteAddr
func (_m *AuthHandler) UpdateRecord(rec *auth.Rec, secret []byte, remoteAddr string) (*auth.Rec, error) {
	ret := _m.Called(rec, secret, remoteAddr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecord")
	}

	var r0 *auth.Rec
	var r1 error
	if rf, ok := ret.Get(0).(func(*auth.Rec, []byte, string) (*auth.Rec, error)); ok {
		return rf(rec, secret, remoteAddr)
	}
	if rf, ok := ret.Get(0).(func(*auth.Rec, []byte, string) *auth.Rec); ok {
		r0 = rf(rec, secret, remoteAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Rec)
		}
	}

	if rf, ok := ret.Get(1).(func(*auth.Rec, []byte, string) error); ok {
		r1 = rf(rec, secret, remoteAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
