// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/tinode/chat/server/store/types"
)

// DevicePersistenceInterface is an autogenerated mock type for the DevicePersistenceInterface type
type DevicePersistenceInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: uid, deviceID
func (_m *DevicePersistenceInterface) Delete(uid types.Uid, deviceID string) error {
	ret := _m.Called(uid, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) error); ok {
		r0 = rf(uid, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: uid
func (_m *DevicePersistenceInterface) GetAll(uid ...types.Uid) (map[types.Uid][]types.DeviceDef, int, error) {
	_va := make([]interface{}, len(uid))
	for _i := range uid {
		_va[_i] = uid[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[types.Uid][]types.DeviceDef
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(...types.Uid) (map[types.Uid][]types.DeviceDef, int, error)); ok {
		return rf(uid...)
	}
	if rf, ok := ret.Get(0).(func(...types.Uid) map[types.Uid][]types.DeviceDef); ok {
		r0 = rf(uid...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.Uid][]types.DeviceDef)
		}
	}

	if rf, ok := ret.Get(1).(func(...types.Uid) int); ok {
		r1 = rf(uid...)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(...types.Uid) error); ok {
		r2 = rf(uid...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: uid, oldDeviceID, dev
func (_m *DevicePersistenceInterface) Update(uid types.Uid, oldDeviceID string, dev *types.DeviceDef) error {
	ret := _m.Called(uid, oldDeviceID, dev)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string, *types.DeviceDef) error); ok {
		r0 = rf(uid, oldDeviceID, dev)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDevicePersistenceInterface creates a new instance of DevicePersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDevicePersistenceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DevicePersistenceInterface {
	mock := &DevicePersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
