// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"

	types "github.com/tinode/chat/server/store/types"
)

// FilePersistenceInterface is an autogenerated mock type for the FilePersistenceInterface type
type FilePersistenceInterface struct {
	mock.Mock
}

// DeleteUnused provides a mock function with given fields: olderThan, limit
func (_m *FilePersistenceInterface) DeleteUnused(olderThan time.Time, limit int) error {
	ret := _m.Called(olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnused")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time, int) error); ok {
		r0 = rf(olderThan, limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinishUpload provides a mock function with given fields: fd, success, size
func (_m *FilePersistenceInterface) FinishUpload(fd *types.FileDef, success bool, size int64) (*types.FileDef, error) {
	ret := _m.Called(fd, success, size)

	if len(ret) == 0 {
		panic("no return value specified for FinishUpload")
	}

	var r0 *types.FileDef
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.FileDef, bool, int64) (*types.FileDef, error)); ok {
		return rf(fd, success, size)
	}
	if rf, ok := ret.Get(0).(func(*types.FileDef, bool, int64) *types.FileDef); ok {
		r0 = rf(fd, success, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.FileDef)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.FileDef, bool, int64) error); ok {
		r1 = rf(fd, success, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: fid
func (_m *FilePersistenceInterface) Get(fid string) (*types.FileDef, error) {
	ret := _m.Called(fid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.FileDef
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.FileDef, error)); ok {
		return rf(fid)
	}
	if rf, ok := ret.Get(0).(func(string) *types.FileDef); ok {
		r0 = rf(fid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.FileDef)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkAttachments provides a mock function with given fields: topic, msgId, attachments
func (_m *FilePersistenceInterface) LinkAttachments(topic string, msgId types.Uid, attachments []string) error {
	ret := _m.Called(topic, msgId, attachments)

	if len(ret) == 0 {
		panic("no return value specified for LinkAttachments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, types.Uid, []string) error); ok {
		r0 = rf(topic, msgId, attachments)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartUpload provides a mock function with given fields: fd
func (_m *FilePersistenceInterface) StartUpload(fd *types.FileDef) error {
	ret := _m.Called(fd)

	if len(ret) == 0 {
		panic("no return value specified for StartUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.FileDef) error); ok {
		r0 = rf(fd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFilePersistenceInterface creates a new instance of FilePersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFilePersistenceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *FilePersistenceInterface {
	mock := &FilePersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
