// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/tinode/chat/server/store/types"
)

// MessagesPersistenceInterface is an autogenerated mock type for the MessagesPersistenceInterface type
type MessagesPersistenceInterface struct {
	mock.Mock
}

// DeleteList provides a mock function with given fields: topic, delID, forUser, ranges
func (_m *MessagesPersistenceInterface) DeleteList(topic string, delID int, forUser types.Uid, ranges []types.Range) error {
	ret := _m.Called(topic, delID, forUser, ranges)

	if len(ret) == 0 {
		panic("no return value specified for DeleteList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, types.Uid, []types.Range) error); ok {
		r0 = rf(topic, delID, forUser, ranges)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: topic, forUser, opt
func (_m *MessagesPersistenceInterface) GetAll(topic string, forUser types.Uid, opt *types.QueryOpt) ([]types.Message, error) {
	ret := _m.Called(topic, forUser, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []types.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.Uid, *types.QueryOpt) ([]types.Message, error)); ok {
		return rf(topic, forUser, opt)
	}
	if rf, ok := ret.Get(0).(func(string, types.Uid, *types.QueryOpt) []types.Message); ok {
		r0 = rf(topic, forUser, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.Uid, *types.QueryOpt) error); ok {
		r1 = rf(topic, forUser, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDeleted provides a mock function with given fields: topic, forUser, opt
func (_m *MessagesPersistenceInterface) GetDeleted(topic string, forUser types.Uid, opt *types.QueryOpt) ([]types.Range, int, error) {
	ret := _m.Called(topic, forUser, opt)

	if len(ret) == 0 {
		panic("no return value specified for GetDeleted")
	}

	var r0 []types.Range
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, types.Uid, *types.QueryOpt) ([]types.Range, int, error)); ok {
		return rf(topic, forUser, opt)
	}
	if rf, ok := ret.Get(0).(func(string, types.Uid, *types.QueryOpt) []types.Range); ok {
		r0 = rf(topic, forUser, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Range)
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.Uid, *types.QueryOpt) int); ok {
		r1 = rf(topic, forUser, opt)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, types.Uid, *types.QueryOpt) error); ok {
		r2 = rf(topic, forUser, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: msg, attachmentURLs, readBySender
func (_m *MessagesPersistenceInterface) Save(msg *types.Message, attachmentURLs []string, readBySender bool) (error, bool) {
	ret := _m.Called(msg, attachmentURLs, readBySender)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	var r1 bool
	if rf, ok := ret.Get(0).(func(*types.Message, []string, bool) (error, bool)); ok {
		return rf(msg, attachmentURLs, readBySender)
	}
	if rf, ok := ret.Get(0).(func(*types.Message, []string, bool) error); ok {
		r0 = rf(msg, attachmentURLs, readBySender)
	} else {
		r0 = ret.Error(0)
	}

	if rf, ok := ret.Get(1).(func(*types.Message, []string, bool) bool); ok {
		r1 = rf(msg, attachmentURLs, readBySender)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewMessagesPersistenceInterface creates a new instance of MessagesPersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagesPersistenceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagesPersistenceInterface {
	mock := &MessagesPersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
