// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PersistentCacheInterface is an autogenerated mock type for the PersistentCacheInterface type
type PersistentCacheInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *PersistentCacheInterface) Delete(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Expire provides a mock function with given fields: keyPrefix, olderThan
func (_m *PersistentCacheInterface) Expire(keyPrefix string, olderThan time.Time) error {
	ret := _m.Called(keyPrefix, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Time) error); ok {
		r0 = rf(keyPrefix, olderThan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *PersistentCacheInterface) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: key, value, failOnDuplicate
func (_m *PersistentCacheInterface) Upsert(key string, value string, failOnDuplicate bool) error {
	ret := _m.Called(key, value, failOnDuplicate)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool) error); ok {
		r0 = rf(key, value, failOnDuplicate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPersistentCacheInterface creates a new instance of PersistentCacheInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersistentCacheInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersistentCacheInterface {
	mock := &PersistentCacheInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
