// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	auth "github.com/tinode/chat/server/auth"
	adapter "github.com/tinode/chat/server/db"

	json "encoding/json"

	media "github.com/tinode/chat/server/media"

	mock "github.com/stretchr/testify/mock"

	types "github.com/tinode/chat/server/store/types"

	validate "github.com/tinode/chat/server/validate"
)

// PersistentStorageInterface is an autogenerated mock type for the PersistentStorageInterface type
type PersistentStorageInterface struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *PersistentStorageInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DbStats provides a mock function with no fields
func (_m *PersistentStorageInterface) DbStats() func() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DbStats")
	}

	var r0 func() interface{}
	if rf, ok := ret.Get(0).(func() func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() interface{})
		}
	}

	return r0
}

// GetAdapter provides a mock function with no fields
func (_m *PersistentStorageInterface) GetAdapter() adapter.Adapter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAdapter")
	}

	var r0 adapter.Adapter
	if rf, ok := ret.Get(0).(func() adapter.Adapter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(adapter.Adapter)
		}
	}

	return r0
}

// GetAdapterName provides a mock function with no fields
func (_m *PersistentStorageInterface) GetAdapterName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAdapterName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAdapterVersion provides a mock function with no fields
func (_m *PersistentStorageInterface) GetAdapterVersion() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAdapterVersion")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetAuthHandler provides a mock function with given fields: name
func (_m *PersistentStorageInterface) GetAuthHandler(name string) auth.AuthHandler {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthHandler")
	}

	var r0 auth.AuthHandler
	if rf, ok := ret.Get(0).(func(string) auth.AuthHandler); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.AuthHandler)
		}
	}

	return r0
}

// GetAuthNames provides a mock function with no fields
func (_m *PersistentStorageInterface) GetAuthNames() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthNames")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetDbVersion provides a mock function with no fields
func (_m *PersistentStorageInterface) GetDbVersion() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDbVersion")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetLogicalAuthHandler provides a mock function with given fields: name
func (_m *PersistentStorageInterface) GetLogicalAuthHandler(name string) auth.AuthHandler {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetLogicalAuthHandler")
	}

	var r0 auth.AuthHandler
	if rf, ok := ret.Get(0).(func(string) auth.AuthHandler); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.AuthHandler)
		}
	}

	return r0
}

// GetMediaHandler provides a mock function with no fields
func (_m *PersistentStorageInterface) GetMediaHandler() media.Handler {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMediaHandler")
	}

	var r0 media.Handler
	if rf, ok := ret.Get(0).(func() media.Handler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(media.Handler)
		}
	}

	return r0
}

// GetUid provides a mock function with no fields
func (_m *PersistentStorageInterface) GetUid() types.Uid {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUid")
	}

	var r0 types.Uid
	if rf, ok := ret.Get(0).(func() types.Uid); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.Uid)
	}

	return r0
}

// GetUidString provides a mock function with no fields
func (_m *PersistentStorageInterface) GetUidString() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUidString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetValidator provides a mock function with given fields: name
func (_m *PersistentStorageInterface) GetValidator(name string) validate.Validator {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetValidator")
	}

	var r0 validate.Validator
	if rf, ok := ret.Get(0).(func(string) validate.Validator); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(validate.Validator)
		}
	}

	return r0
}

// InitDb provides a mock function with given fields: jsonconf, reset
func (_m *PersistentStorageInterface) InitDb(jsonconf json.RawMessage, reset bool) error {
	ret := _m.Called(jsonconf, reset)

	if len(ret) == 0 {
		panic("no return value specified for InitDb")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(json.RawMessage, bool) error); ok {
		r0 = rf(jsonconf, reset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsOpen provides a mock function with no fields
func (_m *PersistentStorageInterface) IsOpen() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsOpen")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Open provides a mock function with given fields: workerId, jsonconf
func (_m *PersistentStorageInterface) Open(workerId int, jsonconf json.RawMessage) error {
	ret := _m.Called(workerId, jsonconf)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, json.RawMessage) error); ok {
		r0 = rf(workerId, jsonconf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpgradeDb provides a mock function with given fields: jsonconf
func (_m *PersistentStorageInterface) UpgradeDb(jsonconf json.RawMessage) error {
	ret := _m.Called(jsonconf)

	if len(ret) == 0 {
		panic("no return value specified for UpgradeDb")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(json.RawMessage) error); ok {
		r0 = rf(jsonconf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UseMediaHandler provides a mock function with given fields: name, config
func (_m *PersistentStorageInterface) UseMediaHandler(name string, config string) error {
	ret := _m.Called(name, config)

	if len(ret) == 0 {
		panic("no return value specified for UseMediaHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPersistentStorageInterface creates a new instance of PersistentStorageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersistentStorageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersistentStorageInterface {
	mock := &PersistentStorageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
