// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/tinode/chat/server/store/types"
)

// SubsPersistenceInterface is an autogenerated mock type for the SubsPersistenceInterface type
type SubsPersistenceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: subs
func (_m *SubsPersistenceInterface) Create(subs ...*types.Subscription) error {
	_va := make([]interface{}, len(subs))
	for _i := range subs {
		_va[_i] = subs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...*types.Subscription) error); ok {
		r0 = rf(subs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: topic, user
func (_m *SubsPersistenceInterface) Delete(topic string, user types.Uid) error {
	ret := _m.Called(topic, user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, types.Uid) error); ok {
		r0 = rf(topic, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: topic, user, keepDeleted
func (_m *SubsPersistenceInterface) Get(topic string, user types.Uid, keepDeleted bool) (*types.Subscription, error) {
	ret := _m.Called(topic, user, keepDeleted)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, types.Uid, bool) (*types.Subscription, error)); ok {
		return rf(topic, user, keepDeleted)
	}
	if rf, ok := ret.Get(0).(func(string, types.Uid, bool) *types.Subscription); ok {
		r0 = rf(topic, user, keepDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, types.Uid, bool) error); ok {
		r1 = rf(topic, user, keepDeleted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: topic, user, update
func (_m *SubsPersistenceInterface) Update(topic string, user types.Uid, update map[string]interface{}) error {
	ret := _m.Called(topic, user, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, types.Uid, map[string]interface{}) error); ok {
		r0 = rf(topic, user, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubsPersistenceInterface creates a new instance of SubsPersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubsPersistenceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubsPersistenceInterface {
	mock := &SubsPersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
