// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/tinode/chat/server/store/types"
)

// TopicsPersistenceInterface is an autogenerated mock type for the TopicsPersistenceInterface type
type TopicsPersistenceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: topic, owner, private
func (_m *TopicsPersistenceInterface) Create(topic *types.Topic, owner types.Uid, private interface{}) error {
	ret := _m.Called(topic, owner, private)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Topic, types.Uid, interface{}) error); ok {
		r0 = rf(topic, owner, private)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateP2P provides a mock function with given fields: initiator, invited
func (_m *TopicsPersistenceInterface) CreateP2P(initiator *types.Subscription, invited *types.Subscription) error {
	ret := _m.Called(initiator, invited)

	if len(ret) == 0 {
		panic("no return value specified for CreateP2P")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Subscription, *types.Subscription) error); ok {
		r0 = rf(initiator, invited)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: topic, isChan, hard
func (_m *TopicsPersistenceInterface) Delete(topic string, isChan bool, hard bool) error {
	ret := _m.Called(topic, isChan, hard)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool, bool) error); ok {
		r0 = rf(topic, isChan, hard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: topic
func (_m *TopicsPersistenceInterface) Get(topic string) (*types.Topic, error) {
	ret := _m.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.Topic, error)); ok {
		return rf(topic)
	}
	if rf, ok := ret.Get(0).(func(string) *types.Topic); ok {
		r0 = rf(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(topic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubs provides a mock function with given fields: topic, opts
func (_m *TopicsPersistenceInterface) GetSubs(topic string, opts *types.QueryOpt) ([]types.Subscription, error) {
	ret := _m.Called(topic, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetSubs")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) ([]types.Subscription, error)); ok {
		return rf(topic, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) []types.Subscription); ok {
		r0 = rf(topic, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *types.QueryOpt) error); ok {
		r1 = rf(topic, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubsAny provides a mock function with given fields: topic, opts
func (_m *TopicsPersistenceInterface) GetSubsAny(topic string, opts *types.QueryOpt) ([]types.Subscription, error) {
	ret := _m.Called(topic, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetSubsAny")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) ([]types.Subscription, error)); ok {
		return rf(topic, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) []types.Subscription); ok {
		r0 = rf(topic, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *types.QueryOpt) error); ok {
		r1 = rf(topic, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: topic, opts
func (_m *TopicsPersistenceInterface) GetUsers(topic string, opts *types.QueryOpt) ([]types.Subscription, error) {
	ret := _m.Called(topic, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) ([]types.Subscription, error)); ok {
		return rf(topic, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) []types.Subscription); ok {
		r0 = rf(topic, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *types.QueryOpt) error); ok {
		r1 = rf(topic, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersAny provides a mock function with given fields: topic, opts
func (_m *TopicsPersistenceInterface) GetUsersAny(topic string, opts *types.QueryOpt) ([]types.Subscription, error) {
	ret := _m.Called(topic, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersAny")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) ([]types.Subscription, error)); ok {
		return rf(topic, opts)
	}
	if rf, ok := ret.Get(0).(func(string, *types.QueryOpt) []types.Subscription); ok {
		r0 = rf(topic, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *types.QueryOpt) error); ok {
		r1 = rf(topic, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OwnerChange provides a mock function with given fields: topic, newOwner
func (_m *TopicsPersistenceInterface) OwnerChange(topic string, newOwner types.Uid) error {
	ret := _m.Called(topic, newOwner)

	if len(ret) == 0 {
		panic("no return value specified for OwnerChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, types.Uid) error); ok {
		r0 = rf(topic, newOwner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: topic, update
func (_m *TopicsPersistenceInterface) Update(topic string, update map[string]interface{}) error {
	ret := _m.Called(topic, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(topic, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTopicsPersistenceInterface creates a new instance of TopicsPersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopicsPersistenceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopicsPersistenceInterface {
	mock := &TopicsPersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
