// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	auth "github.com/tinode/chat/server/auth"

	time "time"

	types "github.com/tinode/chat/server/store/types"
)

// UsersPersistenceInterface is an autogenerated mock type for the UsersPersistenceInterface type
type UsersPersistenceInterface struct {
	mock.Mock
}

// AddAuthRecord provides a mock function with given fields: uid, authLvl, scheme, unique, secret, expires
func (_m *UsersPersistenceInterface) AddAuthRecord(uid types.Uid, authLvl auth.Level, scheme string, unique string, secret []byte, expires time.Time) error {
	ret := _m.Called(uid, authLvl, scheme, unique, secret, expires)

	if len(ret) == 0 {
		panic("no return value specified for AddAuthRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, auth.Level, string, string, []byte, time.Time) error); ok {
		r0 = rf(uid, authLvl, scheme, unique, secret, expires)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmCred provides a mock function with given fields: id, method
func (_m *UsersPersistenceInterface) ConfirmCred(id types.Uid, method string) error {
	ret := _m.Called(id, method)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmCred")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) error); ok {
		r0 = rf(id, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: user, private
func (_m *UsersPersistenceInterface) Create(user *types.User, private interface{}) (*types.User, error) {
	ret := _m.Called(user, private)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.User, interface{}) (*types.User, error)); ok {
		return rf(user, private)
	}
	if rf, ok := ret.Get(0).(func(*types.User, interface{}) *types.User); ok {
		r0 = rf(user, private)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.User, interface{}) error); ok {
		r1 = rf(user, private)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DelAuthRecords provides a mock function with given fields: uid, scheme
func (_m *UsersPersistenceInterface) DelAuthRecords(uid types.Uid, scheme string) error {
	ret := _m.Called(uid, scheme)

	if len(ret) == 0 {
		panic("no return value specified for DelAuthRecords")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) error); ok {
		r0 = rf(uid, scheme)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelCred provides a mock function with given fields: id, method, value
func (_m *UsersPersistenceInterface) DelCred(id types.Uid, method string, value string) error {
	ret := _m.Called(id, method, value)

	if len(ret) == 0 {
		panic("no return value specified for DelCred")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string, string) error); ok {
		r0 = rf(id, method, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id, hard
func (_m *UsersPersistenceInterface) Delete(id types.Uid, hard bool) error {
	ret := _m.Called(id, hard)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, bool) error); ok {
		r0 = rf(id, hard)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FailCred provides a mock function with given fields: id, method
func (_m *UsersPersistenceInterface) FailCred(id types.Uid, method string) error {
	ret := _m.Called(id, method)

	if len(ret) == 0 {
		panic("no return value specified for FailCred")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) error); ok {
		r0 = rf(id, method)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindSubs provides a mock function with given fields: id, required, optional, activeOnly
func (_m *UsersPersistenceInterface) FindSubs(id types.Uid, required [][]string, optional []string, activeOnly bool) ([]types.Subscription, error) {
	ret := _m.Called(id, required, optional, activeOnly)

	if len(ret) == 0 {
		panic("no return value specified for FindSubs")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, [][]string, []string, bool) ([]types.Subscription, error)); ok {
		return rf(id, required, optional, activeOnly)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, [][]string, []string, bool) []types.Subscription); ok {
		r0 = rf(id, required, optional, activeOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid, [][]string, []string, bool) error); ok {
		r1 = rf(id, required, optional, activeOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: uid
func (_m *UsersPersistenceInterface) Get(uid types.Uid) (*types.User, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid) (*types.User, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(types.Uid) *types.User); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.User)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveCred provides a mock function with given fields: id, method
func (_m *UsersPersistenceInterface) GetActiveCred(id types.Uid, method string) (*types.Credential, error) {
	ret := _m.Called(id, method)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveCred")
	}

	var r0 *types.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) (*types.Credential, error)); ok {
		return rf(id, method)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, string) *types.Credential); ok {
		r0 = rf(id, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid, string) error); ok {
		r1 = rf(id, method)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: uid
func (_m *UsersPersistenceInterface) GetAll(uid ...types.Uid) ([]types.User, error) {
	_va := make([]interface{}, len(uid))
	for _i := range uid {
		_va[_i] = uid[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []types.User
	var r1 error
	if rf, ok := ret.Get(0).(func(...types.Uid) ([]types.User, error)); ok {
		return rf(uid...)
	}
	if rf, ok := ret.Get(0).(func(...types.Uid) []types.User); ok {
		r0 = rf(uid...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.User)
		}
	}

	if rf, ok := ret.Get(1).(func(...types.Uid) error); ok {
		r1 = rf(uid...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCreds provides a mock function with given fields: id, method, validatedOnly
func (_m *UsersPersistenceInterface) GetAllCreds(id types.Uid, method string, validatedOnly bool) ([]types.Credential, error) {
	ret := _m.Called(id, method, validatedOnly)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCreds")
	}

	var r0 []types.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, string, bool) ([]types.Credential, error)); ok {
		return rf(id, method, validatedOnly)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, string, bool) []types.Credential); ok {
		r0 = rf(id, method, validatedOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid, string, bool) error); ok {
		r1 = rf(id, method, validatedOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAuthRecord provides a mock function with given fields: user, scheme
func (_m *UsersPersistenceInterface) GetAuthRecord(user types.Uid, scheme string) (string, auth.Level, []byte, time.Time, error) {
	ret := _m.Called(user, scheme)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthRecord")
	}

	var r0 string
	var r1 auth.Level
	var r2 []byte
	var r3 time.Time
	var r4 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) (string, auth.Level, []byte, time.Time, error)); ok {
		return rf(user, scheme)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, string) string); ok {
		r0 = rf(user, scheme)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(types.Uid, string) auth.Level); ok {
		r1 = rf(user, scheme)
	} else {
		r1 = ret.Get(1).(auth.Level)
	}

	if rf, ok := ret.Get(2).(func(types.Uid, string) []byte); ok {
		r2 = rf(user, scheme)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]byte)
		}
	}

	if rf, ok := ret.Get(3).(func(types.Uid, string) time.Time); ok {
		r3 = rf(user, scheme)
	} else {
		r3 = ret.Get(3).(time.Time)
	}

	if rf, ok := ret.Get(4).(func(types.Uid, string) error); ok {
		r4 = rf(user, scheme)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// GetAuthUniqueRecord provides a mock function with given fields: scheme, unique
func (_m *UsersPersistenceInterface) GetAuthUniqueRecord(scheme string, unique string) (types.Uid, auth.Level, []byte, time.Time, error) {
	ret := _m.Called(scheme, unique)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthUniqueRecord")
	}

	var r0 types.Uid
	var r1 auth.Level
	var r2 []byte
	var r3 time.Time
	var r4 error
	if rf, ok := ret.Get(0).(func(string, string) (types.Uid, auth.Level, []byte, time.Time, error)); ok {
		return rf(scheme, unique)
	}
	if rf, ok := ret.Get(0).(func(string, string) types.Uid); ok {
		r0 = rf(scheme, unique)
	} else {
		r0 = ret.Get(0).(types.Uid)
	}

	if rf, ok := ret.Get(1).(func(string, string) auth.Level); ok {
		r1 = rf(scheme, unique)
	} else {
		r1 = ret.Get(1).(auth.Level)
	}

	if rf, ok := ret.Get(2).(func(string, string) []byte); ok {
		r2 = rf(scheme, unique)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]byte)
		}
	}

	if rf, ok := ret.Get(3).(func(string, string) time.Time); ok {
		r3 = rf(scheme, unique)
	} else {
		r3 = ret.Get(3).(time.Time)
	}

	if rf, ok := ret.Get(4).(func(string, string) error); ok {
		r4 = rf(scheme, unique)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// GetByCred provides a mock function with given fields: method, value
func (_m *UsersPersistenceInterface) GetByCred(method string, value string) (types.Uid, error) {
	ret := _m.Called(method, value)

	if len(ret) == 0 {
		panic("no return value specified for GetByCred")
	}

	var r0 types.Uid
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (types.Uid, error)); ok {
		return rf(method, value)
	}
	if rf, ok := ret.Get(0).(func(string, string) types.Uid); ok {
		r0 = rf(method, value)
	} else {
		r0 = ret.Get(0).(types.Uid)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(method, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannels provides a mock function with given fields: id
func (_m *UsersPersistenceInterface) GetChannels(id types.Uid) ([]string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetChannels")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid) ([]string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(types.Uid) []string); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOwnTopics provides a mock function with given fields: id
func (_m *UsersPersistenceInterface) GetOwnTopics(id types.Uid) ([]string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnTopics")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid) ([]string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(types.Uid) []string); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubs provides a mock function with given fields: id
func (_m *UsersPersistenceInterface) GetSubs(id types.Uid) ([]types.Subscription, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubs")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid) ([]types.Subscription, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(types.Uid) []types.Subscription); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopics provides a mock function with given fields: id, opts
func (_m *UsersPersistenceInterface) GetTopics(id types.Uid, opts *types.QueryOpt) ([]types.Subscription, error) {
	ret := _m.Called(id, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetTopics")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, *types.QueryOpt) ([]types.Subscription, error)); ok {
		return rf(id, opts)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, *types.QueryOpt) []types.Subscription); ok {
		r0 = rf(id, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid, *types.QueryOpt) error); ok {
		r1 = rf(id, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTopicsAny provides a mock function with given fields: id, opts
func (_m *UsersPersistenceInterface) GetTopicsAny(id types.Uid, opts *types.QueryOpt) ([]types.Subscription, error) {
	ret := _m.Called(id, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetTopicsAny")
	}

	var r0 []types.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, *types.QueryOpt) ([]types.Subscription, error)); ok {
		return rf(id, opts)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, *types.QueryOpt) []types.Subscription); ok {
		r0 = rf(id, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid, *types.QueryOpt) error); ok {
		r1 = rf(id, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnreadCount provides a mock function with given fields: ids
func (_m *UsersPersistenceInterface) GetUnreadCount(ids ...types.Uid) (map[types.Uid]int, error) {
	_va := make([]interface{}, len(ids))
	for _i := range ids {
		_va[_i] = ids[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 map[types.Uid]int
	var r1 error
	if rf, ok := ret.Get(0).(func(...types.Uid) (map[types.Uid]int, error)); ok {
		return rf(ids...)
	}
	if rf, ok := ret.Get(0).(func(...types.Uid) map[types.Uid]int); ok {
		r0 = rf(ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.Uid]int)
		}
	}

	if rf, ok := ret.Get(1).(func(...types.Uid) error); ok {
		r1 = rf(ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnvalidated provides a mock function with given fields: lastUpdatedBefore, limit
func (_m *UsersPersistenceInterface) GetUnvalidated(lastUpdatedBefore time.Time, limit int) ([]types.Uid, error) {
	ret := _m.Called(lastUpdatedBefore, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnvalidated")
	}

	var r0 []types.Uid
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, int) ([]types.Uid, error)); ok {
		return rf(lastUpdatedBefore, limit)
	}
	if rf, ok := ret.Get(0).(func(time.Time, int) []types.Uid); ok {
		r0 = rf(lastUpdatedBefore, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Uid)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, int) error); ok {
		r1 = rf(lastUpdatedBefore, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: uid, update
func (_m *UsersPersistenceInterface) Update(uid types.Uid, update map[string]interface{}) error {
	ret := _m.Called(uid, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, map[string]interface{}) error); ok {
		r0 = rf(uid, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAuthRecord provides a mock function with given fields: uid, authLvl, scheme, unique, secret, expires
func (_m *UsersPersistenceInterface) UpdateAuthRecord(uid types.Uid, authLvl auth.Level, scheme string, unique string, secret []byte, expires time.Time) error {
	ret := _m.Called(uid, authLvl, scheme, unique, secret, expires)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, auth.Level, string, string, []byte, time.Time) error); ok {
		r0 = rf(uid, authLvl, scheme, unique, secret, expires)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastSeen provides a mock function with given fields: uid, userAgent, when
func (_m *UsersPersistenceInterface) UpdateLastSeen(uid types.Uid, userAgent string, when time.Time) error {
	ret := _m.Called(uid, userAgent, when)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string, time.Time) error); ok {
		r0 = rf(uid, userAgent, when)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateState provides a mock function with given fields: uid, state
func (_m *UsersPersistenceInterface) UpdateState(uid types.Uid, state types.ObjState) error {
	ret := _m.Called(uid, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, types.ObjState) error); ok {
		r0 = rf(uid, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTags provides a mock function with given fields: uid, add, remove, reset
func (_m *UsersPersistenceInterface) UpdateTags(uid types.Uid, add []string, remove []string, reset []string) ([]string, error) {
	ret := _m.Called(uid, add, remove, reset)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, []string, []string, []string) ([]string, error)); ok {
		return rf(uid, add, remove, reset)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, []string, []string, []string) []string); ok {
		r0 = rf(uid, add, remove, reset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(types.Uid, []string, []string, []string) error); ok {
		r1 = rf(uid, add, remove, reset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertCred provides a mock function with given fields: cred
func (_m *UsersPersistenceInterface) UpsertCred(cred *types.Credential) (bool, error) {
	ret := _m.Called(cred)

	if len(ret) == 0 {
		panic("no return value specified for UpsertCred")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.Credential) (bool, error)); ok {
		return rf(cred)
	}
	if rf, ok := ret.Get(0).(func(*types.Credential) bool); ok {
		r0 = rf(cred)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*types.Credential) error); ok {
		r1 = rf(cred)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUsersPersistenceInterface creates a new instance of UsersPersistenceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersPersistenceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersPersistenceInterface {
	mock := &UsersPersistenceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
