// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
	push "github.com/tinode/chat/server/push"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Channel provides a mock function with no fields
func (_m *Handler) Channel() chan<- *push.ChannelReq {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 chan<- *push.ChannelReq
	if rf, ok := ret.Get(0).(func() chan<- *push.ChannelReq); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan<- *push.ChannelReq)
		}
	}

	return r0
}

// Init provides a mock function with given fields: jsonconf
func (_m *Handler) Init(jsonconf json.RawMessage) (bool, error) {
	ret := _m.Called(jsonconf)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(json.RawMessage) (bool, error)); ok {
		return rf(jsonconf)
	}
	if rf, ok := ret.Get(0).(func(json.RawMessage) bool); ok {
		r0 = rf(jsonconf)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(json.RawMessage) error); ok {
		r1 = rf(jsonconf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsReady provides a mock function with no fields
func (_m *Handler) IsReady() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReady")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Push provides a mock function with no fields
func (_m *Handler) Push() chan<- *push.Receipt {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 chan<- *push.Receipt
	if rf, ok := ret.Get(0).(func() chan<- *push.Receipt); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan<- *push.Receipt)
		}
	}

	return r0
}

// Stop provides a mock function with no fields
func (_m *Handler) Stop() {
	_m.Called()
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
