// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "github.com/tinode/chat/server/store/types"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

// Check provides a mock function with given fields: user, resp
func (_m *Validator) Check(user types.Uid, resp string) (string, error) {
	ret := _m.Called(user, resp)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) (string, error)); ok {
		return rf(user, resp)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, string) string); ok {
		r0 = rf(user, resp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(types.Uid, string) error); ok {
		r1 = rf(user, resp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: user
func (_m *Validator) Delete(user types.Uid) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields: jsonconf
func (_m *Validator) Init(jsonconf string) error {
	ret := _m.Called(jsonconf)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(jsonconf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsInitialized provides a mock function with no fields
func (_m *Validator) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PreCheck provides a mock function with given fields: cred, params
func (_m *Validator) PreCheck(cred string, params map[string]interface{}) (string, error) {
	ret := _m.Called(cred, params)

	if len(ret) == 0 {
		panic("no return value specified for PreCheck")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) (string, error)); ok {
		return rf(cred, params)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) string); ok {
		r0 = rf(cred, params)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(cred, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: user, value
func (_m *Validator) Remove(user types.Uid, value string) error {
	ret := _m.Called(user, value)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Uid, string) error); ok {
		r0 = rf(user, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Request provides a mock function with given fields: user, cred, lang, resp, tmpToken
func (_m *Validator) Request(user types.Uid, cred string, lang string, resp string, tmpToken []byte) (bool, error) {
	ret := _m.Called(user, cred, lang, resp, tmpToken)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(types.Uid, string, string, string, []byte) (bool, error)); ok {
		return rf(user, cred, lang, resp, tmpToken)
	}
	if rf, ok := ret.Get(0).(func(types.Uid, string, string, string, []byte) bool); ok {
		r0 = rf(user, cred, lang, resp, tmpToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(types.Uid, string, string, string, []byte) error); ok {
		r1 = rf(user, cred, lang, resp, tmpToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetSecret provides a mock function with given fields: cred, scheme, lang, tmpToken, params
func (_m *Validator) ResetSecret(cred string, scheme string, lang string, tmpToken []byte, params map[string]interface{}) error {
	ret := _m.Called(cred, scheme, lang, tmpToken, params)

	if len(ret) == 0 {
		panic("no return value specified for ResetSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, []byte, map[string]interface{}) error); ok {
		r0 = rf(cred, scheme, lang, tmpToken, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TempAuthScheme provides a mock function with no fields
func (_m *Validator) TempAuthScheme() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TempAuthScheme")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
