// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// formatter is an autogenerated mock type for the formatter type
type formatter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: n, state
func (_m *formatter) Execute(n *drafty.node, state interface{}) error {
	ret := _m.Called(n, state)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*drafty.node, interface{}) error); ok {
		r0 = rf(n, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newFormatter creates a new instance of formatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFormatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *formatter {
	mock := &formatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
