// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isClientMsg_Message is an autogenerated mock type for the isClientMsg_Message type
type isClientMsg_Message struct {
	mock.Mock
}

// isClientMsg_Message provides a mock function with no fields
func (_m *isClientMsg_Message) isClientMsg_Message() {
	_m.Called()
}

// newIsClientMsg_Message creates a new instance of isClientMsg_Message. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsClientMsg_Message(t interface {
	mock.TestingT
	Cleanup(func())
}) *isClientMsg_Message {
	mock := &isClientMsg_Message{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
