// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isServerMsg_Message is an autogenerated mock type for the isServerMsg_Message type
type isServerMsg_Message struct {
	mock.Mock
}

// isServerMsg_Message provides a mock function with no fields
func (_m *isServerMsg_Message) isServerMsg_Message() {
	_m.Called()
}

// newIsServerMsg_Message creates a new instance of isServerMsg_Message. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsServerMsg_Message(t interface {
	mock.TestingT
	Cleanup(func())
}) *isServerMsg_Message {
	mock := &isServerMsg_Message{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
