// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pbx "github.com/tinode/chat/pbx"
)

// NodeServer is an autogenerated mock type for the NodeServer type
type NodeServer struct {
	mock.Mock
}

// MessageLoop provides a mock function with given fields: _a0
func (_m *NodeServer) MessageLoop(_a0 pbx.Node_MessageLoopServer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for MessageLoop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pbx.Node_MessageLoopServer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mustEmbedUnimplementedNodeServer provides a mock function with no fields
func (_m *NodeServer) mustEmbedUnimplementedNodeServer() {
	_m.Called()
}

// NewNodeServer creates a new instance of NodeServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeServer {
	mock := &NodeServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
