// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pbx "github.com/tinode/chat/pbx"
)

// PluginClient is an autogenerated mock type for the PluginClient type
type PluginClient struct {
	mock.Mock
}

// Account provides a mock function with given fields: ctx, in, opts
func (_m *PluginClient) Account(ctx context.Context, in *pbx.AccountEvent, opts ...grpc.CallOption) (*pbx.Unused, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.AccountEvent, ...grpc.CallOption) (*pbx.Unused, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.AccountEvent, ...grpc.CallOption) *pbx.Unused); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.AccountEvent, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, in, opts
func (_m *PluginClient) Find(ctx context.Context, in *pbx.SearchQuery, opts ...grpc.CallOption) (*pbx.SearchFound, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *pbx.SearchFound
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SearchQuery, ...grpc.CallOption) (*pbx.SearchFound, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SearchQuery, ...grpc.CallOption) *pbx.SearchFound); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.SearchFound)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.SearchQuery, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FireHose provides a mock function with given fields: ctx, in, opts
func (_m *PluginClient) FireHose(ctx context.Context, in *pbx.ClientReq, opts ...grpc.CallOption) (*pbx.ServerResp, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FireHose")
	}

	var r0 *pbx.ServerResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.ClientReq, ...grpc.CallOption) (*pbx.ServerResp, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.ClientReq, ...grpc.CallOption) *pbx.ServerResp); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.ServerResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.ClientReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Message provides a mock function with given fields: ctx, in, opts
func (_m *PluginClient) Message(ctx context.Context, in *pbx.MessageEvent, opts ...grpc.CallOption) (*pbx.Unused, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.MessageEvent, ...grpc.CallOption) (*pbx.Unused, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.MessageEvent, ...grpc.CallOption) *pbx.Unused); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.MessageEvent, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscription provides a mock function with given fields: ctx, in, opts
func (_m *PluginClient) Subscription(ctx context.Context, in *pbx.SubscriptionEvent, opts ...grpc.CallOption) (*pbx.Unused, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscription")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SubscriptionEvent, ...grpc.CallOption) (*pbx.Unused, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SubscriptionEvent, ...grpc.CallOption) *pbx.Unused); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.SubscriptionEvent, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Topic provides a mock function with given fields: ctx, in, opts
func (_m *PluginClient) Topic(ctx context.Context, in *pbx.TopicEvent, opts ...grpc.CallOption) (*pbx.Unused, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.TopicEvent, ...grpc.CallOption) (*pbx.Unused, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.TopicEvent, ...grpc.CallOption) *pbx.Unused); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.TopicEvent, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPluginClient creates a new instance of PluginClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginClient {
	mock := &PluginClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
