// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	pbx "github.com/tinode/chat/pbx"
)

// PluginServer is an autogenerated mock type for the PluginServer type
type PluginServer struct {
	mock.Mock
}

// Account provides a mock function with given fields: _a0, _a1
func (_m *PluginServer) Account(_a0 context.Context, _a1 *pbx.AccountEvent) (*pbx.Unused, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.AccountEvent) (*pbx.Unused, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.AccountEvent) *pbx.Unused); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.AccountEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: _a0, _a1
func (_m *PluginServer) Find(_a0 context.Context, _a1 *pbx.SearchQuery) (*pbx.SearchFound, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *pbx.SearchFound
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SearchQuery) (*pbx.SearchFound, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SearchQuery) *pbx.SearchFound); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.SearchFound)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.SearchQuery) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FireHose provides a mock function with given fields: _a0, _a1
func (_m *PluginServer) FireHose(_a0 context.Context, _a1 *pbx.ClientReq) (*pbx.ServerResp, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for FireHose")
	}

	var r0 *pbx.ServerResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.ClientReq) (*pbx.ServerResp, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.ClientReq) *pbx.ServerResp); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.ServerResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.ClientReq) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Message provides a mock function with given fields: _a0, _a1
func (_m *PluginServer) Message(_a0 context.Context, _a1 *pbx.MessageEvent) (*pbx.Unused, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.MessageEvent) (*pbx.Unused, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.MessageEvent) *pbx.Unused); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.MessageEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscription provides a mock function with given fields: _a0, _a1
func (_m *PluginServer) Subscription(_a0 context.Context, _a1 *pbx.SubscriptionEvent) (*pbx.Unused, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Subscription")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SubscriptionEvent) (*pbx.Unused, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.SubscriptionEvent) *pbx.Unused); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.SubscriptionEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Topic provides a mock function with given fields: _a0, _a1
func (_m *PluginServer) Topic(_a0 context.Context, _a1 *pbx.TopicEvent) (*pbx.Unused, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 *pbx.Unused
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.TopicEvent) (*pbx.Unused, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pbx.TopicEvent) *pbx.Unused); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pbx.Unused)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pbx.TopicEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedPluginServer provides a mock function with no fields
func (_m *PluginServer) mustEmbedUnimplementedPluginServer() {
	_m.Called()
}

// NewPluginServer creates a new instance of PluginServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginServer {
	mock := &PluginServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
