// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeNodeServer is an autogenerated mock type for the UnsafeNodeServer type
type UnsafeNodeServer struct {
	mock.Mock
}

// mustEmbedUnimplementedNodeServer provides a mock function with no fields
func (_m *UnsafeNodeServer) mustEmbedUnimplementedNodeServer() {
	_m.Called()
}

// NewUnsafeNodeServer creates a new instance of UnsafeNodeServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeNodeServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeNodeServer {
	mock := &UnsafeNodeServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
