// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePluginServer is an autogenerated mock type for the UnsafePluginServer type
type UnsafePluginServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPluginServer provides a mock function with no fields
func (_m *UnsafePluginServer) mustEmbedUnimplementedPluginServer() {
	_m.Called()
}

// NewUnsafePluginServer creates a new instance of UnsafePluginServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafePluginServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafePluginServer {
	mock := &UnsafePluginServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
